---

- name: Reload kernel modules
  ansible.builtin.systemd_service:
    name: systemd-modules-load
    state: restarted

- name: Restart firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    state: restarted

- name: Enable WireGuard service
  ansible.builtin.systemd_service:
    name: wireguard
    daemon_reload: true
    enabled: true
    state: started
