---

- name: Service files installed
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/etc/containers/systemd/{{ item }}'
    mode: '0644'
  loop:
    - qbittorrent.container
    - qbittorrent-config.volume
    - qbittorrent-downloads.volume
  notify:
    - "qbittorrent : Enable qBittorrent service"
