---

- name: Configure required kernel modules
  ansible.builtin.copy:
    src: wireguard.conf
    dest: /etc/modules-load.d/wireguard.conf
    mode: '0644'
  notify:
    - "wireguard : Reload kernel modules"

- name: Enable masquerading with firewalld
  ansible.posix.firewalld:
    masquerade: true
    zone: public
    permanent: true
    state: enabled
  notify:
    - "wireguard : Restart firewalld"

- name: Service files installed
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/etc/containers/systemd/{{ item }}'
    mode: '0644'
  loop:
    - wireguard.container
    - wireguard-config.volume
  notify:
    - "wireguard : Enable WireGuard service"
